services:
  es-zenith:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: es-zenith
    environment:
      - node.name=es-zenith
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - network.host=0.0.0.0
    ports:
      - "9200:9200"  # Expose Elasticsearch on port 9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data  # Persistent storage for data
    networks:
      - elastic

  kib-zenith:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kib-zenith
    environment:
      - SERVER_NAME=kib-zenith
      - ELASTICSEARCH_HOSTS=http://es-zenith:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"  # Expose Kibana on port 5601
    depends_on:
      - es-zenith
    networks:
      - elastic

volumes:
  esdata1:
    driver: local

networks:
  elastic:
    driver: bridge
